# Week 4 Checkin - Logistic Regression

In [1]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [2]:
%pip install openpyxl

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.figure_factory as ff
import plotly.graph_objects as go
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import matplotlib.pyplot as plt


In [3]:
logistic_data_orig = pd.read_excel('clean_data.xlsx')
logistic_data_orig

Unnamed: 0                track_id                 artists  \
0               0  5SuOikwiRyPMVoIQDJUgSV             Gen Hoshino   
1               1  4qPNDBW1i3p13qLCt0Ki3A            Ben Woodward   
2               2  1iJBSr7s7jYXzM8EGcbK5b  Ingrid Michaelson;ZAYN   
3               3  6lfxq3CG4xtTiEg7opyCyx            Kina Grannis   
4               4  5vjLSffimiIP26QG5WcN2K        Chord Overstreet   
...           ...                     ...                     ...   
88727      113995  2C3TZjDRiAzdyViavDJ217           Rainy Lullaby   
88728      113996  1hIz5L4IB9hN3WRYPOCGPw           Rainy Lullaby   
88729      113997  6x8ZfSoqDjuNa5SVP5QjvX           Cesária Evora   
88730      113998  2e6sXL2bYv4bSz6VTdnfLs        Michael W. Smith   
88731      113999  2hETkH7cOfqmz3LqZDHZf5           Cesária Evora   

                                              album_name  \
0                                                 Comedy   
1                                       Ghost (Acoustic)   
2                                         To Begin Again   
3      Crazy Rich Asians (Original Motion Picture Sou...   
4                                                Hold On   
...                                                  ...   
88727  #mindfulness - Soft Rain for Mindful Meditatio...   
88728  #mindfulness - Soft Rain for Mindful Meditatio...   
88729                                            Best Of   
88730                                  Change Your World   
88731                                     Miss Perfumado   

                       track_name  popularity  duration_ms  explicit  \
0                          Comedy          73       230666     False   
1                Ghost - Acoustic          55       149610     False   
2                  To Begin Again          57       210826     False   
3      Can't Help Falling In Love          71       201933     False   
4                         Hold On          82       198853     False   
...                           ...         ...          ...       ...   
88727         Sleep My Little Boy          21       384999     False   
88728            Water Into Light          22       385000     False   
88729              Miss Perfumado          22       271466     False   
88730                     Friends          41       283893     False   
88731                   Barbincor          22       241826     False   

       danceability  energy  ...  loudness  mode  speechiness  acousticness  \
0             0.676  0.4610  ...    -6.746     0       0.1430        0.0322   
1             0.420  0.1660  ...   -17.235     1       0.0763        0.9240   
2             0.438  0.3590  ...    -9.734     1       0.0557        0.2100   
3             0.266  0.0596  ...   -18.515     1       0.0363        0.9050   
4             0.618  0.4430  ...    -9.681     1       0.0526        0.4690   
...             ...     ...  ...       ...   ...          ...           ...   
88727         0.172  0.2350  ...   -16.393     1       0.0422        0.6400   
88728         0.174  0.1170  ...   -18.318     0       0.0401        0.9940   
88729         0.629  0.3290  ...   -10.895     0       0.0420        0.8670   
88730         0.587  0.5060  ...   -10.889     1       0.0297        0.3810   
88731         0.526  0.4870  ...   -10.204     0       0.0725        0.6810   

       instrumentalness  liveness  valence    tempo  time_signature  \
0              0.000001    0.3580   0.7150   87.917               4   
1              0.000006    0.1010   0.2670   77.489               4   
2              0.000000    0.1170   0.1200   76.332               4   
3              0.000071    0.1320   0.1430  181.740               3   
4              0.000000    0.0829   0.1670  119.949               4   
...                 ...       ...      ...      ...             ...   
88727          0.928000    0.0863   0.0339  125.995               5   
88728          0.976000    0.1050   0.0350   85.239               4   
8872

In [5]:
logistic_data_orig.sample(7)

Unnamed: 0                track_id  \
35906       40668  1gPl1vIBXFwInMXHJ5Ug7Y   
37846       42748  7BE5qh8793eRFmk55hrhxk   
41098       46659  43hnPF1sJYgCpo9DDZglac   
82873      106702  6Yks2lkGxBNs7u9qw57riG   
61291       74253  2luLDXlcVQmuQ3HARbIDgr   
63521       76780  1eqdiz5chKkoa7BWmDYPBI   
39548       44971  3KcJEOyaLDLAERlOCBhmPA   

                                   artists           album_name  \
35906                           Oficina G3     Depois da Guerra   
37846                 Extreme Noise Terror          Retrobution   
41098                        Scooter;VASSY                Today   
82873                         Jebase;Xeinn              changes   
61291                         Ana Gabriela  Do Quarto Pro Mundo   
63521  André Rieu;Johann Strauss Orchestra  Viva Olympia (Live)   
39548                            Pearl Jam                  Ten   

                       track_name  popularity  duration_ms  explicit  \
35906                       A Ele          40       280589     False   
37846                  Subliminal          12       254600     False   
41098                       Today          19       207256     False   
82873                     changes          31       163422      True   
61291                     3 Horas          44       166573     False   
63521  Amigos Para Siempre - Live          20       301333     False   
39548                      Garden          55       298933     False   

       danceability  energy  ...  loudness  mode  speechiness  acousticness  \
35906         0.159   0.790  ...    -4.829     0       0.0593      0.173000   
37846         0.241   0.882  ...    -8.735     1       0.0792      0.000003   
41098         0.632   0.884  ...    -4.545     0       0.0350      0.002250   
82873         0.704   0.536  ...   -10.748     0       0.0302      0.403000   
61291         0.566   0.483  ...   -10.660     1       0.0313      0.562000   
63521         0.179   0.657  ...    -6.959     1       0.0692      0.887000   
39548         0.191   0.707  ...    -6.846     1       0.0345      0.047800   

       instrumentalness  liveness  valence    tempo  time_signature  \
35906          0.000000    0.0986    0.149  173.385               3   
37846          0.692000    0.1140    0.237  109.698               4   
41098          0.003590    0.3280    0.260  131.947               4   
82873          0.278000    0.3420    0.155  130.022               4   
61291          0.000400    0.0973    0.323  142.793               4   
63521          0.000000    0.9750    0.293   79.059               3   
39548          0.000061    0.2950    0.179   82.700               4   

       track_genre  
35906       gospel  
37846    grindcore  
41098        happy  
82873      swedish  
61291          mpb  
63521        opera  
39548       grunge  

[7 rows x 21 columns]


---


## Fitting logistic regression to the full training dataset


Next, compute a logistic regression fit for the entire training dataset:

In [6]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Separate the features and target variable
X = logistic_data_orig[["instrumentalness", "speechiness", "energy", "valence", "danceability", "acousticness"]]

y = (logistic_data_orig['popularity'] > 30).astype(int)  # Convert to binary: 1 if popularity > 33, else 0

# Apply LabelEncoder to each categorical column in X
for col in X.select_dtypes(include='object').columns:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])

# Split data into training, validation, and test sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Fit the logistic regression model with binary target
lr_all = LogisticRegression(solver='liblinear')
lr_all.fit(X_train, y_train)

# View intercept and coefficients
print("Intercept:", lr_all.intercept_)
print("Coefficients:", lr_all.coef_)




Intercept: [0.17933063]
Coefficients: [[-0.96508481 -2.19179382 -0.10068603 -0.76492574  1.34050641 -0.04720315]]


In [7]:
# Randomly select 50 sample indices from X_val
sample_indices = np.random.choice(X_val.index, size=50, replace=False)

# Select samples from X_val and y_val using the random indices
X_val_sample = X_val.loc[sample_indices, :]
y_val_sample = y_val.loc[sample_indices]

# Predict probabilities and classes for the sample
y_val_pred_probs = lr_all.predict_proba(X_val_sample)[:, 1]  # Probability for the positive class
y_val_pred_classes = lr_all.predict(X_val_sample)

# Create a DataFrame to display actual vs. predicted
evaluation_df = pd.DataFrame({
    'Is popular': y_val_sample,
    'Predicted Probability': y_val_pred_probs,
    'Predicted Popularity': y_val_pred_classes
})

# Display the evaluation DataFrame
print(evaluation_df)


       Is popular  Predicted Probability  Predicted Popularity
80215           0               0.552950                     1
7064            0               0.556474                     1
76303           1               0.545120                     1
19582           0               0.613512                     1
35943           1               0.602341                     1
57440           1               0.577727                     1
26424           0               0.517528                     1
6651            0               0.233589                     0
41881           1               0.441318                     0
24903           0               0.313606                     0
66248           1               0.574225                     1
18331           1               0.641022                     1
69032           0               0.595452                     1
34272           0               0.484577                     0
3288            1               0.493827               

In [8]:
y_val_pred = lr_all.predict(X_val)
conf_lr = metrics.confusion_matrix(y_true=y_val, y_pred=y_val_pred)
conf_lr

array([[2943, 5169],
       [2195, 7440]], dtype=int64)

Prediction accuracy:

In [9]:
# Logistic regression
(conf_lr[0, 0] + conf_lr[1, 1]) / conf_lr.sum()

0.5850566292894573

***Predicted probability densities***


In [10]:
px.histogram(evaluation_df, x='Predicted Probability', color='Is popular',
             nbins=20, opacity=0.5,
             barmode='overlay')



***ROC Curve***

In [11]:
lr_fpr_sample, lr_tpr_sample, lr_thresholds_sample = metrics.roc_curve(evaluation_df['Is popular'], evaluation_df['Predicted Probability'])

lr_thresholds_sample


array([       inf, 0.66656459, 0.66527918, 0.64209152, 0.64208388,
       0.6420179 , 0.62483505, 0.61522178, 0.61436637, 0.61351169,
       0.60830041, 0.60764575, 0.60234084, 0.59745198, 0.59576061,
       0.59159147, 0.58779586, 0.58266174, 0.57422526, 0.56716526,
       0.55989948, 0.55294999, 0.54512034, 0.49580249, 0.49382651,
       0.48457717, 0.39588225, 0.31360569, 0.24300344, 0.17452674])

In [12]:
roc_lr_sample = pd.DataFrame({
    'False Positive Rate': lr_fpr_sample,
    'True Positive Rate': lr_tpr_sample,
    'Model': 'Logistic Regression'
}, index=lr_thresholds_sample)


roc_sample_df = pd.concat([roc_lr_sample])


px.line(roc_sample_df, y='True Positive Rate', x='False Positive Rate',
        color='Model',
        width=700, height=500
)

In [14]:
# Logistic regression
lr_auc_sample = metrics.roc_auc_score(evaluation_df['Is popular'], evaluation_df['Predicted Probability'])
print('Logistic regression AUC:', lr_auc_sample.round(3))

Logistic regression AUC: 0.597


***USING CV FOR MODEL PERFORMANCE***

In [15]:
from sklearn.model_selection import cross_val_score


# Separate the features and target variable
X = logistic_data_orig[["instrumentalness", "speechiness", "energy", "valence", "danceability", "acousticness"]]

y = (logistic_data_orig['popularity'] > 30).astype(int)  # Convert to binary: 1 if popularity > 33, else 0

# This does stratified Kfolds for us...
cross_val_score(lr_all, X, y, cv=5, scoring='roc_auc')

array([0.61194458, 0.61632333, 0.62607415, 0.53816304, 0.48793798])

In [16]:
from sklearn.model_selection import StratifiedKFold
from sklearn.base import clone

# Use the shuffle and random state if want data shuffled before splitting
#skfolds = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
skfolds = StratifiedKFold(n_splits=5)
i = 1
for train_index, test_index in skfolds.split(X, y):
    clone_lr = clone(lr_all)
    X_train_folds = X.iloc[train_index]
    y_train_folds = y.iloc[train_index]
    X_test_fold = X.iloc[test_index]
    print(test_index)
    clone_lr.fit(X_train_folds, y_train_folds)
    y_pred = clone_lr.predict(X_test_fold)

    auc_sample = metrics.roc_auc_score(y.iloc[test_index], y_pred)
    print('Fold: ', i)
    print('AUC: ', auc_sample)
    print('Accuracy: ', metrics.accuracy_score(y.iloc[test_index], y_pred))
    i += 1

[    0     1     2 ... 19686 19687 19689]
Fold:  1
AUC:  0.5793129726060839
Accuracy:  0.5916492928382262
[17120 17121 17122 ... 36795 36796 36797]
Fold:  2
AUC:  0.583511244232712
Accuracy:  0.599199864765876
[34994 34995 34996 ... 57555 57556 57557]
Fold:  3
AUC:  0.5884538204495349
Accuracy:  0.6043051955370224
[50360 50361 50362 ... 73050 73056 73057]
Fold:  4
AUC:  0.5262817018206203
Accuracy:  0.543615462639468
[67736 67737 67738 ... 88729 88730 88731]
Fold:  5
AUC:  0.4887287537481254
Accuracy:  0.5067620872309253
